FROM node:22-alpine

WORKDIR /app

RUN npm install -g nodemon tsx

COPY package.json package-lock.json ./
RUN npm install

COPY tsconfig.json ./
COPY src ./src

EXPOSE 4000

CMD ["npm", "run", "dev"]
